common:
  daemonize: true
  pid_dir: /var/run/
  log_media: file
  log_level: info
  log_dir: /var/log/
  working_dir: .
config_paths:
  config_dir: /usr/local/etc/crowdsec/
  data_dir: /var/db/crowdsec/data/
  simulation_path: /usr/local/etc/crowdsec/simulation.yaml
  hub_dir: /usr/local/etc/crowdsec/hub/
  index_path: /usr/local/etc/crowdsec/hub/.index.json
  notification_dir: /usr/local/etc/crowdsec/notifications/
  plugin_dir: /usr/local/lib/crowdsec/plugins/
crowdsec_service:
  acquisition_path: /usr/local/etc/crowdsec/acquis.yaml
  parser_routines: 1
cscli:
  output: human
db_config:
  log_level: info
  type: sqlite
  db_path: /var/db/crowdsec/data/crowdsec.db
  #user: 
  #password:
  #db_name:
  #host:
  #port:
  flush:
    max_items: 5000
    max_age: 7d
plugin_config:
  user: nobody # plugin process would be ran on behalf of this user
  group: nogroup # plugin process would be ran on behalf of this group
api:
  client:
    insecure_skip_verify: false
    credentials_path: /usr/local/etc/crowdsec/local_api_credentials.yaml
  server:
    log_level: info
    listen_uri: 127.0.0.1:8080
    profiles_path: /usr/local/etc/crowdsec/profiles.yaml
    console_path: /usr/local/etc/crowdsec/console_config.yaml
    online_client: # Central API credentials (to push signals and receive bad IPs)
      credentials_path: /usr/local/etc/crowdsec/online_api_credentials.yaml
#    tls:
#      cert_file: /usr/local/etc/crowdsec/ssl/cert.pem
#      key_file: /usr/local/etc/crowdsec/ssl/key.pem
prometheus:
  enabled: true
  level: full
  listen_addr: 127.0.0.1
  listen_port: 6060
